# Intro to Pandas
### About
- Pandas: Panel Datasets is a fast, powerful, flexible, and easy to use open source data analysis and perp tool.
- It's built on top of NumPy
- Widely used in DS and ML applications for handling **structured** data.
- It has 2 main data components: 
    - Series: 1-dim data object
    - Dataframe: 2-dim data object

### Features
![f](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/1_Introduction_to_Pandas/Features_of_Pandas.png)

pip install pandas

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.2'

## Pandas Series

In [3]:
my_list = [1,2,3,4,5,7,12,8,9,10,11]

type(my_list)

list

In [4]:
my_list

[1, 2, 3, 4, 5, 7, 12, 8, 9, 10, 11]

In [5]:
#convert a list into a series
my_ser = pd.Series(my_list)
my_ser

0      1
1      2
2      3
3      4
4      5
5      7
6     12
7      8
8      9
9     10
10    11
dtype: int64

In [6]:
my_ser[6]

np.int64(12)

In [7]:
ny_ser_v2 = my_ser[3:9]
ny_ser_v2

3     4
4     5
5     7
6    12
7     8
8     9
dtype: int64

In [8]:
# to reset the index (start from 0)
ny_ser_v2 = my_ser[3:9].reset_index(drop=True) #it gets rid of the old index
ny_ser_v2

0     4
1     5
2     7
3    12
4     8
5     9
dtype: int64

In [9]:
my_ser3 = pd.Series([11,12,13], index=['x','y','z'])
my_ser3

x    11
y    12
z    13
dtype: int64

In [10]:
my_ser3['x']

np.int64(11)

In [11]:
import numpy as np

In [12]:
# converting numpy to pandas
my_ser4 = pd.Series(np.arange(2,30))
my_ser4

0      2
1      3
2      4
3      5
4      6
5      7
6      8
7      9
8     10
9     11
10    12
11    13
12    14
13    15
14    16
15    17
16    18
17    19
18    20
19    21
20    22
21    23
22    24
23    25
24    26
25    27
26    28
27    29
dtype: int64

In [13]:
# convert pandas to numpy
my_ser4.values

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Pandas Dataframes

![ad](https://static.packt-cdn.com/products/9781839213106/graphics/Images/B15597_01_01.png)

In [14]:
#dictionary 
data = {'name':['Mark', 'Mike', 'Tammy', 'Becky'],
        'age':[55,43,28,35],
        'score':[96,84,79,83]
        }

In [15]:
#convert data dict into a dataframe
df = pd.DataFrame(data)
df

    name  age  score
0   Mark   55     96
1   Mike   43     84
2  Tammy   28     79
3  Becky   35     83

In [16]:
print(df)

    name  age  score
0   Mark   55     96
1   Mike   43     84
2  Tammy   28     79
3  Becky   35     83

In [17]:
# get the num of rows and cols
df.shape

(4, 3)

In [18]:
#get data types
df.dtypes

name     object
age       int64
score     int64
dtype: object

In [19]:
df.ndim

2

In [20]:
len(df)

4

### Slicing and Dicing Data Using `loc[]` and `iloc[]`

In [21]:
#get the first row
df.loc[0]

name     Mark
age        55
score      96
Name: 0, dtype: object

In [22]:
# get multiple rows by index - first and third row
df.loc[[0,2]]

    name  age  score
0   Mark   55     96
2  Tammy   28     79

In [23]:
df.loc[:2] #loc is an exception to the end point (it gets included)

    name  age  score
0   Mark   55     96
1   Mike   43     84
2  Tammy   28     79

In [24]:
# get all rows and  age and score columns
df.loc[:,['age', 'score']]

   age  score
0   55     96
1   43     84
2   28     79
3   35     83

Compares to SQL: `SELECT age, score FROM df`

Using `loc[]` as a filter

In [25]:
df.loc[df['age']>40]

   name  age  score
0  Mark   55     96
1  Mike   43     84

In [26]:
df[df['age']>40] #no need to use loc in this example

   name  age  score
0  Mark   55     96
1  Mike   43     84

In [27]:
# use case where loc becomes useful
df.loc[df['age']>40, ['age', 'score']]

   age  score
0   55     96
1   43     84

In [28]:
df[(df['age']>40)&(df['score']<95)]

   name  age  score
1  Mike   43     84

Using `iloc[]`

In [29]:
# select first 2 rows with first 2 cols
df.iloc[:2,:2]

   name  age
0  Mark   55
1  Mike   43

In [30]:
df

    name  age  score
0   Mark   55     96
1   Mike   43     84
2  Tammy   28     79
3  Becky   35     83

In [31]:
# you can use negative indices in iloc
df.iloc[-1]

name     Becky
age         35
score       83
Name: 3, dtype: object

In [32]:
df.iloc[-1,-1] #[row position, col position]

np.int64(83)

In [33]:
#select all rows and last 2 columns
df.iloc[:, 1:]

   age  score
0   55     96
1   43     84
2   28     79
3   35     83

In [34]:
df.iloc[:, -2:]

   age  score
0   55     96
1   43     84
2   28     79
3   35     83

**Summary**
- Use `loc[]`
    - You need to access data using row index and the header name
    - column position might change, and you want to ensure that you are accessing the correct column by name
    - the column name must be stable 
    - you want the code more readable 
- Use `iloc[]`
    - You need to access data using indices by their positions
    - The column name might change, and you want to ensure that you are accessing the correct column by position
    - the column position must be stable

In [35]:
# creating a dataframe from lists

data = [['Mark', 'Mike', 'Tammy', 'Becky'],
        [55,43,28,35],
        [96,84,79,83]
        ]

type(data)

list

In [36]:
df = pd.DataFrame(data)
df

      0     1      2      3
0  Mark  Mike  Tammy  Becky
1    55    43     28     35
2    96    84     79     83

In [37]:
df = df.T #transpose
df

       0   1   2
0   Mark  55  96
1   Mike  43  84
2  Tammy  28  79
3  Becky  35  83

In [38]:
# rename the columns
df.columns = ['Names', 'Age', 'Score']
df

   Names Age Score
0   Mark  55    96
1   Mike  43    84
2  Tammy  28    79
3  Becky  35    83

In [39]:
# do everything in one shot
df = pd.DataFrame(data, index=['Names', 'Age', 'Score']).T
df

   Names Age Score
0   Mark  55    96
1   Mike  43    84
2  Tammy  28    79
3  Becky  35    83

## Pandas Iteration Methods

In [40]:
#dictionary 
data = {'name':['Mark', 'Mike', 'Tammy', 'Becky', 'John'],
        'age':[55,43,28,35, 38],
        'score':[96,84,79,83,88],
        'city':['New York', 'Nashville', 'Atlanta', 'Boston', 'San Diego']
        }

df = pd.DataFrame(data)
df

    name  age  score       city
0   Mark   55     96   New York
1   Mike   43     84  Nashville
2  Tammy   28     79    Atlanta
3  Becky   35     83     Boston
4   John   38     88  San Diego

In [41]:
print(f"{df.loc[0,'name']} is {df.loc[0,'age']} years old")

Mark is 55 years old

#### Method 1 - Using the `df.index`

In [42]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [43]:
for i in df.index:
    print(f"{df.loc[i,'name']} is {df.loc[i,'age']} years old")

Mark is 55 years old
Mike is 43 years old
Tammy is 28 years old
Becky is 35 years old
John is 38 years old

#### Method 2 - Using `iterrows()`

In [44]:
for i, row in df.iterrows():
    print(f"Person {i+1}: {row['name']} is {row['age']} years old - location {row['city']}")

Person 1: Mark is 55 years old - location New York
Person 2: Mike is 43 years old - location Nashville
Person 3: Tammy is 28 years old - location Atlanta
Person 4: Becky is 35 years old - location Boston
Person 5: John is 38 years old - location San Diego

In [45]:
# before editing the df, it's recommended to make a backup of it
df_org = df.copy()

In [46]:
df_org

    name  age  score       city
0   Mark   55     96   New York
1   Mike   43     84  Nashville
2  Tammy   28     79    Atlanta
3  Becky   35     83     Boston
4   John   38     88  San Diego

In [47]:
# increase the age of the people by 5 years
df['age'] = df['age'] + 5
df

    name  age  score       city
0   Mark   60     96   New York
1   Mike   48     84  Nashville
2  Tammy   33     79    Atlanta
3  Becky   40     83     Boston
4   John   43     88  San Diego

In [48]:
## create a column that indicates whether the person has a discount based on age > 43
df['discount'] = df['age'].apply(lambda x: 'yes' if x > 40 else 'no')
df

    name  age  score       city discount
0   Mark   60     96   New York      yes
1   Mike   48     84  Nashville      yes
2  Tammy   33     79    Atlanta       no
3  Becky   40     83     Boston       no
4   John   43     88  San Diego      yes

```SQL
SELECT name, age, score, city,
    CASE WHEN age > 40 THEN 'yes'
    ELSE 'no'
    END AS discount
FROM df
```

Applying a defined function instead of `lambda`

In [49]:
def age_categ(row):
    if row['age'] > 50:
        return 'Senior'
    elif row['age'] > 40:
        return 'Mid-Age'
    else:
        return 'Junior'

In [50]:
df['age_category'] = df.apply(age_categ, axis=1)
df

    name  age  score       city discount age_category
0   Mark   60     96   New York      yes       Senior
1   Mike   48     84  Nashville      yes      Mid-Age
2  Tammy   33     79    Atlanta       no       Junior
3  Becky   40     83     Boston       no       Junior
4   John   43     88  San Diego      yes      Mid-Age

In [51]:
def age_categ(x):
    if x > 50:
        return 'Senior'
    elif x > 40:
        return 'Mid-Age'
    else:
        return 'Junior'
    
df['age_category'] = df['age'].apply(age_categ)
df

    name  age  score       city discount age_category
0   Mark   60     96   New York      yes       Senior
1   Mike   48     84  Nashville      yes      Mid-Age
2  Tammy   33     79    Atlanta       no       Junior
3  Becky   40     83     Boston       no       Junior
4   John   43     88  San Diego      yes      Mid-Age

In [52]:
# drop a column
df.drop(columns='age_category', inplace=True) #inplace overwrites the exiting df
df

    name  age  score       city discount
0   Mark   60     96   New York      yes
1   Mike   48     84  Nashville      yes
2  Tammy   33     79    Atlanta       no
3  Becky   40     83     Boston       no
4   John   43     88  San Diego      yes

In [53]:
#alternative without inplace
#df = df.drop(columns='age_category')

In [54]:
# insert a column ina  specific location
df.insert(2, 'age_category', df['age'].apply(age_categ))
df

    name  age age_category  score       city discount
0   Mark   60       Senior     96   New York      yes
1   Mike   48      Mid-Age     84  Nashville      yes
2  Tammy   33       Junior     79    Atlanta       no
3  Becky   40       Junior     83     Boston       no
4   John   43      Mid-Age     88  San Diego      yes

### Using `map()`

In [55]:
# create a column that gives us the region of the city in the US
df['region'] = df['city'].map(
                            {
                               'New York': 'North',
                               'Nashville': 'South',
                               'Atlanta':'South',
                               'San Diego':'West',
                               'Boston':'North' 
                            }
                    )

df

    name  age age_category  score       city discount region
0   Mark   60       Senior     96   New York      yes  North
1   Mike   48      Mid-Age     84  Nashville      yes  South
2  Tammy   33       Junior     79    Atlanta       no  South
3  Becky   40       Junior     83     Boston       no  North
4   John   43      Mid-Age     88  San Diego      yes   West

- If you miss a category, `pandas` will apply `NaN`. Also, keep in mind python/pandas are case sensitive.
- No need to repeat the category if it's applicable to multiple values.

Using `replace()`

In [56]:
df['name'] = df['name'].replace({'Mark': 'Jeff', 'Tammy':'Brittney'}) #replacing mark with jeff
df

       name  age age_category  score       city discount region
0      Jeff   60       Senior     96   New York      yes  North
1      Mike   48      Mid-Age     84  Nashville      yes  South
2  Brittney   33       Junior     79    Atlanta       no  South
3     Becky   40       Junior     83     Boston       no  North
4      John   43      Mid-Age     88  San Diego      yes   West

- Use `replace()` to edit existing columns (you don't have to specify every value)
- Use `map()` to create new columns based on an existing column.
- For a full df scan and replace use `df = df.replace(...)`
- `replace` has also RegEx capability which will explore in the future.

### Sorting Data

In [57]:
# for one col
df.sort_values(by='age', inplace=True, ignore_index=True) #ignore index will reset the index 
df

       name  age age_category  score       city discount region
0  Brittney   33       Junior     79    Atlanta       no  South
1     Becky   40       Junior     83     Boston       no  North
2      John   43      Mid-Age     88  San Diego      yes   West
3      Mike   48      Mid-Age     84  Nashville      yes  South
4      Jeff   60       Senior     96   New York      yes  North

In [58]:
# for one col - descending order
df.sort_values(by='age', inplace=True, ignore_index=True, ascending=False) #ignore index will reset the index 
df

       name  age age_category  score       city discount region
0      Jeff   60       Senior     96   New York      yes  North
1      Mike   48      Mid-Age     84  Nashville      yes  South
2      John   43      Mid-Age     88  San Diego      yes   West
3     Becky   40       Junior     83     Boston       no  North
4  Brittney   33       Junior     79    Atlanta       no  South

In [59]:
# for one col
df.sort_values(by=['region','age'], inplace=True, ignore_index=True) #ignore index will reset the index 
df

       name  age age_category  score       city discount region
0     Becky   40       Junior     83     Boston       no  North
1      Jeff   60       Senior     96   New York      yes  North
2  Brittney   33       Junior     79    Atlanta       no  South
3      Mike   48      Mid-Age     84  Nashville      yes  South
4      John   43      Mid-Age     88  San Diego      yes   West

In [60]:
region_order = ['South','North','West']

df['region'] = pd.Categorical(df['region'], categories=region_order, ordered=True)

df.sort_values('region')

       name  age age_category  score       city discount region
2  Brittney   33       Junior     79    Atlanta       no  South
3      Mike   48      Mid-Age     84  Nashville      yes  South
0     Becky   40       Junior     83     Boston       no  North
1      Jeff   60       Senior     96   New York      yes  North
4      John   43      Mid-Age     88  San Diego      yes   West

In [61]:
# sort by name descending and then age ascending
df.sort_values(by=['name','age'], inplace=True, ignore_index=True, ascending=[False, True])
df

       name  age age_category  score       city discount region
0      Mike   48      Mid-Age     84  Nashville      yes  South
1      John   43      Mid-Age     88  San Diego      yes   West
2      Jeff   60       Senior     96   New York      yes  North
3  Brittney   33       Junior     79    Atlanta       no  South
4     Becky   40       Junior     83     Boston       no  North

### Looking for Nulls

In [62]:
#dictionary 
data = {'name':['Mark', 'Mike', 'Tammy', 'Becky', 'John'],
        'age':[55,np.nan,28,35, np.nan],
        'score':[96,84,79,83,np.nan],
        'city':['New York', 'Nashville', 'Atlanta', 'Boston', 'San Diego']
        }

df = pd.DataFrame(data)
df

    name   age  score       city
0   Mark  55.0   96.0   New York
1   Mike   NaN   84.0  Nashville
2  Tammy  28.0   79.0    Atlanta
3  Becky  35.0   83.0     Boston
4   John   NaN    NaN  San Diego

In [63]:
df.isna().sum()

name     0
age      2
score    1
city     0
dtype: int64

In [64]:
df['age'].sort_values()

2    28.0
3    35.0
0    55.0
1     NaN
4     NaN
Name: age, dtype: float64

In [65]:
# get the rows with nulls
df[df.isna().any(axis=1)]

   name  age  score       city
1  Mike  NaN   84.0  Nashville
4  John  NaN    NaN  San Diego

In [66]:
df[~df.isna().any(axis=1)]

    name   age  score      city
0   Mark  55.0   96.0  New York
2  Tammy  28.0   79.0   Atlanta
3  Becky  35.0   83.0    Boston

In [67]:
#instead of using the function above to get non-nulls, use dropna()
df.dropna()

    name   age  score      city
0   Mark  55.0   96.0  New York
2  Tammy  28.0   79.0   Atlanta
3  Becky  35.0   83.0    Boston

In [68]:
df['name'].unique()

array(['Mark', 'Mike', 'Tammy', 'Becky', 'John'], dtype=object)

In [69]:
for val in df['name'].unique():
    print('Count of nulls for',val,df[df['name']==val].isna().sum().sum())

Count of nulls for Mark 0
Count of nulls for Mike 1
Count of nulls for Tammy 0
Count of nulls for Becky 0
Count of nulls for John 2